services:
  app:
    image: elharish/laravel_docker_app:latest
    container_name: laravel_docker_app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - laravel_storage:/var/www/storage
      - laravel_public:/var/www/public       # ← add this
    depends_on:
      db:
        condition: service_healthy
    networks:
      - laravel-docker

  nginx:
    image: nginx:alpine
    container_name: laravel_docker_nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - laravel_storage:/var/www/storage
      - laravel_public:/var/www/public       # ← add this
    depends_on:
      - app
    networks:
      - laravel-docker

volumes:
  laravel_storage:
  laravel_public:                            # ← add this
  db_data: